### ISSUE TITLE
Deep Static Analysis and Unit Testing

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/airship#180] opened 2017-03-16 17:04 UTC
We currently have [Psalm](https://github.com/vimeo/psalm) running in Travis CI on the core files (src/Engine). We should expand the coverage include everything in `src`. We'll have to do each Cabin individually.

**Comment by muglug** [comment] 2017-03-19 18:01
Relatedly, [this curious chunk of code](https://github.com/paragonie/airship/blob/7af4dd4f10f0c307d1b10fdc1f736fd25913e174/src/Engine/Security/Filter/BoolArrayFilter.php#L49-L53) was flagged by latest Psalm `dev-master`.

**Comment by paragonie-scott** [comment] 2017-03-19 18:08
Oh, I should probably change `null` to `[]`? (Composer still hasn't updated.)

**Comment by muglug** [comment] 2017-03-19 18:09
more the `if (!\is_array($data)) {` check on something that is definitely an array (because of the cast)

**Comment by paragonie-scott** [comment] 2017-03-19 18:17
Is there any chance we can just make the `is_*()` functions excluded from type errors?

**Comment by muglug** [comment] 2017-03-19 18:26
They should be excluded when the type comes from a docblock (as opposed to language-level check). I think the difference here is that the `if` is inside a loop, and I imagine I introduced a regression with https://github.com/vimeo/psalm/pull/115. Will fix momentarily.

But still, how can that if statement ever be true?

**Comment by paragonie-scott** [comment] 2017-03-19 18:28
It can't ever be true; it's dead code. I'm removing it in a few seconds. :)

**Comment by muglug** [comment] 2017-03-19 18:41
Fixed in https://github.com/vimeo/psalm/commit/f0964685362dc45e867a6e22de3b4fc28b3a4f6a

**Comment by paragonie-scott** [comment] 2017-04-05 02:17
Left to do before this can be closed (mostly meant as a note to myself so the next time I look through open issues for things to work on, I don't need to try to refresh my own memory):

- [ ] Find out if Psalm can be coerced into specifying a different .xml file from its CLI arguments.
  - [ ] If yes, create a psalm.xml for each Cabin.
  - [ ] If no, rename the existing psalm.xml file and rapidly create/remove symlinks to make it behave. Also, create a psalm.sh script to facilitate this for non-Travis testing.

**Comment by muglug** [comment] 2017-04-05 02:22
You can do `psalm --config=somefile.xml`

**Comment by paragonie-scott** [comment] 2017-04-05 02:22
Perfect! Thanks. :)

**Comment by muglug** [comment] 2017-04-05 02:24
If you're running `--diff` builds locally you'll need to specify different cache directories for them, but I think your codebase is small enough that `--diff` builds aren't necessary.

**Closed** 2018-01-13 03:17 UTC
Labels: community, feedback sought, future, help wanted, quality assurance
